add set rgb_pin

diff --git a/bin/pironman b/bin/pironman
--- a/bin/pironman
+++ b/bin/pironman
@@ -7,46 +7,88 @@
 ####
 #### Options:
 ####   start            start pironman service
+####
 ####   stop             stop pironman service
+####
 ####   restart          restart pironman service
+####
 ####   -h,--help        help, show this help
+####
 ####   -c,--check       show all configurations
+####
 ####   -a,--auto        [ on ],enable auto-start at boot
 ####                    [ off ], disable auto-start at boot
+####
 ####   -u,--unit        [ C/F ], set the unit of temperature,
 ####                        C or F (Celsius/Fahrenheit)
+####
 ####   -f,--fan         [ temp ], Temperature at which the fan switches on,
 ####                    in celsius (default 50),in range (30 ~ 80)
+####
 ####   -al,--always_on  [on/off], whether the screen is always on,
 ####                    default False
+####
 ####   -s,--staty_time  [time], screen display duration in second,
 ####                    in second, default 30
+####
 ####   -rw,--rgb_sw     [on/off], rgb strip switch
+####
 ####   -rs,--rgb_style  rgb strip display style, default: breath,
 ####                    in [breath / leap / flow / raise_up / colorful]
+####
 ####   -rc,--rgb_color  [(HEX)color], set the color of rgb strip,
 ####                    default: 0a1aff
+####
 ####   -rb,--rgb_speed  [speed], rgb blink speed (0 ~ 100, default 50)
 ####
 ####   -pwm,--rgb_pwm   [frequency], rgb signal frequency (400 ~ 1600, default 1000 kHz)
 ####
+####   -rp,--rgb_pin    [pin], rgb signal pin, could be [10 / spi/ SPI / 12 / pwm/ PWM] or
+####                    [21 / pcm / PCM], default 10
+####
 
 main='/opt/pironman/main.py'
 User=$(ls -l $main |awk '{print $3}')
-Group=$(ls -l $main |awk '{print $3}')
 UserHome=$(getent passwd $User |cut -d: -f 6)
 CONF=$UserHome/.config/pironman/config.txt
 
 # echo $main
 # echo $User
-# echo $Group
 # echo $UserHome
 # echo $CONF
 # echo 'config file:'$CONF
 
+# print colors
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+BLUE='\033[0;34m'
+GRAY='\033[1;30m'
+#
+NC='\033[0m'
+
+# check boot configuration path
+BOOT_CONFIG_1="/boot/config.txt"
+BOOT_CONFIG_2="/boot/firmware/config.txt"
+boot_config=""
+
+# check boot configuration path
+if [ -f "$BOOT_CONFIG_1" ]; then
+    boot_config=${BOOT_CONFIG_1}
+elif [ -f $BOOT_CONFIG_2 ]; then
+    boot_config=${BOOT_CONFIG_2}
+else
+    boot_config=""
+    echo -e "${RED}Error: Cannot find boot configuration file${NC}"
+    exit 1
+fi
+
+# echo "boot_config: ${boot_config}"
+##################### ---- fuctions ---- #####################
+
 help() {
-    echo $'\nconfig file: '$CONF
-    sed -rn 's/^#### ?//;T;p;' "$0"
+    echo -e "\nconfig file:${CONF}"
+    sed -rn 's/^#### //; s/^####$//; T; p;' "$0"
 }
 
 start() {
@@ -73,6 +115,26 @@ restart() {
     start
 }
 
+want_reboot() {
+    read -e -p "$(echo -e ${GREEN}Do you want to reboot to make change take effect?\(Y/N\): ${NC} )" choice
+    if [ "$choice" == "Y" ] || [ "$choice" == "y" ]; then
+        echo "Rebooting now..."
+        sudo reboot
+    fi
+}
+
+change_config() {
+    # $1, check str
+    # $2, replace str
+    # $3, config file path
+    if grep -q -e $1 $3; then
+        sudo sed -i -e "s:$1:$2:g" $3
+    else
+        sudo sed -i -e "$ a\[all]\n$2" $3
+    fi
+}
+
+##################### ---- main ---- #####################
 
 if [ $# == 0 ] || [ $1 == '-h' ]|| [ $1 == '--help' ];then
     help
@@ -90,8 +152,8 @@ case "$1" in
         restart
         ;;
     -c|--check)
-        echo 'config file:'$CONF
-        grep -E '*=.*' $CONF
+        echo -e "config file:${CONF}\n"
+        grep -E '*=.*' ${CONF}
         ;;
     -a|--auto)
         case "$2" in
@@ -252,6 +314,60 @@ case "$1" in
                 echo "parameter must be integer"
             fi
         fi
+        ;;
+    -rp|--rgb_pin)
+        case "$2" in
+            spi|SPI|10)
+                echo "set rgb io to pin 10 (spi)"
+                # set pin
+                change_config ".*rgb_pin\s*=.*"  "rgb_pin = 10" ${CONF}
+                #
+                echo "boot_config: ${boot_config}"
+                ## enable audio
+                change_config ".*dtparam=audio=.*" "dtparam=audio=on" ${boot_config}
+                # enable spi
+                change_config ".*dtparam=spi=.*"  "dtparam=spi=on" ${boot_config}
+                # change core_freq, core_freq_min to stabilize the spi output frequency
+                change_config ".*core_freq=.*"  "core_freq=500" ${boot_config}
+                change_config ".*core_freq_min=.*"  "core_freq_min=500" ${boot_config}
+                # whether reboot to make changes take effect
+                want_reboot
+                # restart program
+                restart
+                ;;
+            pwm|PWM|12)
+                echo "set rgb io to pin 12 (pwm)"
+                # set io
+                change_config ".*rgb_pin\s*=.*"  "rgb_pin = 12" ${CONF}
+                #
+                echo "boot_config: ${boot_config}"
+                # disable audio
+                change_config ".*dtparam=audio=.*" "dtparam=audio=off" ${boot_config}
+                # whether reboot to make changes take effect
+                want_reboot
+                # restart program
+                restart
+                ;;
+            pcm|PCM|21)
+                echo "set rgb io to pin 21 (pcm)"
+                # set io
+                change_config ".*rgb_pin\s*=.*"  "rgb_pin = 21" ${CONF}
+                #
+                echo "boot_config: ${boot_config}"
+                 ## enable audio
+                change_config ".*dtparam=audio=.*" "dtparam=audio=on" ${boot_config}
+                # disable i2s
+                change_config ".*dtoverlay=hifiberry-dac$" "#dtoverlay=hifiberry-dac" ${boot_config}
+                change_config ".*dtoverlay=i2s-mmap$" "#dtoverlay=i2s-mmap" ${boot_config}
+                # whether reboot to make changes take effect
+                want_reboot
+                # restart program
+                restart
+                ;;
+            *)
+                echo "usage: pironman -rp|--rgb_pin [10 / spi / 12 / pwm / 21 / pcm]"
+                ;;
+        esac
         ;;
     *)
         echo "no this command: $1"
